# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4.13-cli-buster

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y software-properties-common apt-utils curl zip git libxml2 libxml2-dev
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update --1

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit
